name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output  # garante que estamos no branch certo

      - uses: Platane/snk@v3
        with:
          github_user_name: joaopbcardoso
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: generate contribution snake'
          add: 'dist/*.svg'
          push: origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
