name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, dependendo do seu branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js (se usar build com node, React, etc)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (se usar)
        run: npm install

      - name: Build (se usar)
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # ou ./public, ou a pasta com o site estático
